

white_noise_values = [
    #{"noise_strength_percent": 0.1},
    #{"noise_strength_percent":0.2},
    #{"noise_strength_percent":0.3},
    #{"noise_strength_percent":0.4},
    #{"noise_strength_percent":0.45},
    #{"noise_strength_percent":0.5},
    #{"noise_strength_percent":0.55},
    #{"noise_strength_percent":0.6},
    #{"noise_strength_percent":0.7},
    #{"noise_strength_percent":0.8},
    #{"noise_strength_percent":0.9},
    #{"noise_strength_percent":1},
    {"noise_strength_percent": 1.2},
    {"noise_strength_percent": 1.4},
    {"noise_strength_percent": 1.6},
    {"noise_strength_percent": 1.8},
    {"noise_strength_percent": 2},
    {"noise_strength_percent": 3},
    {"noise_strength_percent": 5},
]

gaussian_noise_values = [
    {"noise_strength_percent": 0.1},
    {"noise_strength_percent":0.2},
    {"noise_strength_percent":0.3},
    {"noise_strength_percent":0.4},
    {"noise_strength_percent":0.45},
    {"noise_strength_percent":0.5},
    {"noise_strength_percent":0.55},
    {"noise_strength_percent":0.6},
    {"noise_strength_percent":0.7},
    {"noise_strength_percent":0.8},
    {"noise_strength_percent":0.9},
    {"noise_strength_percent":1.0},
    {"noise_strength_percent": 1.2},
    {"noise_strength_percent": 1.4},
    {"noise_strength_percent": 1.6},
    {"noise_strength_percent": 1.8},
    {"noise_strength_percent": 2},
    {"noise_strength_percent": 3},
    {"noise_strength_percent": 5},
]