

white_noise_values = [
    {"noise_strength_percent": 0.0},
    {"noise_strength_percent": 0.01},
    {"noise_strength_percent": 0.015},
    {"noise_strength_percent": 0.025},
    {"noise_strength_percent": 0.05},
    {"noise_strength_percent": 0.075},
    #{"noise_strength_percent": 0.1},
    {"noise_strength_percent": 0.15},
    #{"noise_strength_percent":0.2},
    #{"noise_strength_percent":0.3},
    #{"noise_strength_percent":0.4},
    #{"noise_strength_percent":0.45},
    #{"noise_strength_percent":0.5},
    #{"noise_strength_percent":0.55},
    #{"noise_strength_percent":0.6},
    #{"noise_strength_percent":0.7},
    #{"noise_strength_percent":0.8},
    #{"noise_strength_percent":0.9},
    #{"noise_strength_percent":1},
    #{"noise_strength_percent": 1.2},
    #{"noise_strength_percent": 1.4},
    #{"noise_strength_percent": 1.6},
    #{"noise_strength_percent": 1.8},
    #{"noise_strength_percent": 2},
    #{"noise_strength_percent": 3},
    #{"noise_strength_percent": 5},
]

gaussian_noise_values = [
    {"noise_strength_percent": 0.0},
    {"noise_strength_percent": 0.01},
    {"noise_strength_percent": 0.015},
    {"noise_strength_percent": 0.025},
    {"noise_strength_percent": 0.05},
    {"noise_strength_percent": 0.075},
    {"noise_strength_percent": 0.1},
    {"noise_strength_percent": 0.15},
    {"noise_strength_percent":0.2},
    {"noise_strength_percent":0.3},
    {"noise_strength_percent":0.4},
    {"noise_strength_percent":0.45},
    {"noise_strength_percent":0.5},
    {"noise_strength_percent":0.55},
    {"noise_strength_percent":0.6},
    {"noise_strength_percent":0.7},
    {"noise_strength_percent":0.8},
    {"noise_strength_percent":0.9},
    {"noise_strength_percent":1},
    {"noise_strength_percent": 1.2},
    {"noise_strength_percent": 1.4},
    {"noise_strength_percent": 1.6},
    {"noise_strength_percent": 1.8},
    {"noise_strength_percent": 2},
    {"noise_strength_percent": 3},
    {"noise_strength_percent": 5},
]

transient_noise_values = [
    {"noise_strength_percent": 0.0, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent": 0.01, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent": 0.015, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent": 0.025, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent": 0.05, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent": 0.075, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent": 0.1, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent": 0.15, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent":0.2, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent":0.3, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent":0.4, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent":0.45, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent":0.5, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent":0.55, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent":0.6, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent":0.7, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent":0.8, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent":0.9, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent":1, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent": 1.2, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent": 1.4, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent": 1.6, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent": 1.8, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent": 2, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent": 3, "burst_amounts": 1, "burst_length": 150},
    {"noise_strength_percent": 5, "burst_amounts": 1, "burst_length": 150},

    {"noise_strength_percent": 0.01, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 0.015, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 0.025, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 0.05, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 0.075, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 0.1, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 0.15, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 0.2, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 0.3, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 0.4, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 0.45, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 0.5, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 0.55, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 0.6, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 0.7, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 0.8, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 0.9, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 1, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 1.2, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 1.4, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 1.6, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 1.8, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 2, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 3, "burst_amounts": 2, "burst_length": 150},
    {"noise_strength_percent": 5, "burst_amounts": 2, "burst_length": 150},

    {"noise_strength_percent": 0.01, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 0.015, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 0.025, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 0.05, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 0.075, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 0.1, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 0.15, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 0.2, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 0.3, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 0.4, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 0.45, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 0.5, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 0.55, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 0.6, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 0.7, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 0.8, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 0.9, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 1, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 1.2, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 1.4, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 1.6, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 1.8, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 2, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 3, "burst_amounts": 3, "burst_length": 150},
    {"noise_strength_percent": 5, "burst_amounts": 3, "burst_length": 150},
]